spring.application.name=event-management
spring.datasource.url=jdbc:mysql://localhost:3306/event_db
spring.datasource.username=root
spring.datasource.password=swetha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9999